### ISSUE TITLE
iQue Mario Color Code Generating Functionality Request

### ISSUE THREAD

**Issue by 8192Bit** [the404devs/sm64code#2]
Recently I found out memory addresses storing color data of Mario in the game iQue Mario (Chinese version of Super Mario 64).
Could you add a button that can generate Color Code for iQue Mario? Thanks.
***        COLOR CODE ADDRESSES IN IQUE MARIO      ***

Parts			Colors		Address	Type

Hat & Shirt	Main		800610B0	RGB888
			Shadow		800610A8	RGB888
Hair			Main		80061110	RGB888
			Shadow		80061108	RGB888
Skin			Main		800610F8	RGB888
			Shadow		800610F0	RGB888
Gloves		Main		800610C8	RGB888
			Shadow		800610C0	RGB888
Overalls		Main		80061098	RGB888
			Shadow		80061090	RGB888
Shoes		Main		800610E0	RGB888
			Shadow		800610D8	RGB888

**Comment by the404devs** [comment]
Thanks, I've now added iQue support
